pipeline {
    agent any

    environment {
        DOCKERHUB_CREDS = credentials('dockerhub') // Jenkins credential ID
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Preethi-Vijay/devopscourse.git'
            }
        }

        stage('Build Image') {
            steps {
                sh 'docker build -t dockercorona/jenkinstest:$BUILD_NUMBER ./pushdockerimage/'
            }
        }

        stage('Docker Login') {
            steps {
                sh 'echo $DOCKERHUB_CREDS_PSW | docker login -u $DOCKERHUB_CREDS_USR --password-stdin'
            }
        }

        stage('Docker Push') {
            steps {
                sh 'docker push dockercorona/jenkinstest:$BUILD_NUMBER'
            }
        }
    }

    post {
        always {
            sh 'docker logout'
        }
    }
}
