pipeline {
    agent any
    environment {
        DOCKERHUB = credentials('dockerhub')   // match the ID you set in Jenkins
    }
    stages {
        stage('Build Image') {
            steps {
                sh 'docker build -t dockercorona/jenkinstest:$BUILD_NUMBER ./pushdockerimage/'
            }
        }

        stage('Debug Creds') {
            steps {
                // This just prints the username and password length
                sh 'echo "User: $DOCKERHUB_USR"'
                sh 'echo "Password length:" $(echo $DOCKERHUB_PSW | wc -c)'
            }
        }

        stage('Docker Login') {
            steps {
                sh 'echo $DOCKERHUB_PSW | docker login -u $DOCKERHUB_USR --password-stdin'
            }
        }

        stage('Docker Push') {
            steps {
                sh 'docker push dockercorona/jenkinstest:$BUILD_NUMBER'
            }
        }
    }
    post {
        always {
            sh 'docker logout'
        }
    }
}
