pipeline {
    agent any
    environment {
        DOCKERHUB = credentials('dockerhub')  // use the ID from Jenkins credentials
    }
    stages {
        stage('Build Image') {
            steps {
                sh 'docker build -t dockercorona/jenkinstest:$BUILD_NUMBER ./pushdockerimage/'
            }
        }
        stage('Docker Login') {
            steps {
                sh 'echo $DOCKERHUB_PSW | docker login -u $DOCKERHUB_USR --password-stdin'
            }
        }
        stage('Docker Push') {
            steps {
                sh 'docker push dockercorona/jenkinstest:$BUILD_NUMBER'
            }
        }
    }
    post {
        always {
            sh 'docker logout'
        }
    }
}
